config/routes.rb
Rails.application.routes.draw do
  resources :wikis do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  resources :charges, only: [:new, :create, :destroy]

  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'
end

app/models/amount.rb
class Amount < ActiveRecord::Base
  def self.default
    1500
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :collaborators
  has_many :wikis, through: :collaborators
  after_initialize { self.role ||= :standard }

  enum role: [:standard, :premium, :admin]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    # Creates a Stripe Customer object for associating with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "BigMoney Membership - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attributes(role: 'premium')

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to root_path

    #Stripe will send back CardErrors, with friendly messages when something goes wrong.
    #This rescue block catches and displays errors.
    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.name}",
      amount: Amount.default
    }
  end

  def destroy
    current_user.update_attributes(role: 'standard')

    wikis = current_user.wikis
    wikis.each do |w|
      w.update(private: false)
    end

    flash[:notice] = "You have been downgraded. You private wikis are now public."
    redirect_to root_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  before_action :get_wiki

  def index
    @users = User.all
  end

  def new
    @collaborator = Collaborator.new
  end

  def create
    @collaborator = Collaborator.new(wiki_id: @wiki.id, user_id: params[:user_id])

    if @collaborator.save
      flash[:notice] = "collaborator has been added as a collaborator to wiki."
      redirect_to wiki_collaborators_path(@wiki)
    else
      flash[:alert] = "There was an error adding the collaborator. Please try again."
      render :new
    end
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was successfully removed."
    else
      flash[:alert] = "There was an error removing the collaborator. Please try again."
    end
    redirect_to wiki_collaborators_path(@wiki)
  end

  private
  def get_wiki
    @wiki = Wiki.friendly.find(params[:wiki_id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def downgrade
    @user = User.find(params[:id])
    @user.role = 'standard'

    if @user.save
      flash[:notice] = "You have been downgraded. You private wikis are now public."
      redirect_to root_path
    else
      flash[:alert] = "There was an error updating your prfile, try again."
      redirect_to root_path
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
  end

  def create
    @wiki = Wiki.new
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user
    authorize @wiki

    if @wiki.save
      flash[:notice] = 'You have successfully created a new wiki.'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error creating your wiki. Please try again.'
      render :new
    end
  end

  def update
    @wiki = Wiki.friendly.find(params[:id])
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    authorize @wiki

    if @wiki.save
      flash[:notice] = 'You have successfully updated your wiki.'
      redirect_to @wiki
    else
      flash.now[:alert] = 'There was an error updating your wiki. Please try again.'
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.friendly.find(params[:id])
    authorize @wiki
    @wiki.destroy

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was successfully deleted."
      redirect_to wikis_path
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(new_user_session_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
  def not_collaborator?(collaborators, id)
    collaborators.each do |c|
      if c.user_id == id
        break
      end
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_is_premium?
    if user_signed_in?
      current_user.premium?
    else
      false
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def markdown(content)
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, space_after_headers: true, fenced_code_blocks: true)
    @markdown.render(content).html_safe
  end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Please enter credit card info to upgrade your account.</h4>
  <small>You will be charged $15 for a premium account.</small>
</br>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/index.html.erb
<h1 class="text-center">Add Collaborators to the Wiki (showing all users)</h1>
</br>
<h5 class="text-center"><%= link_to "Back to edit wiki", edit_wiki_path(@wiki) %></h5>
<div class="wiki-table">
  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Give Access</th>
    </tr>
    <% @users.each do |user| %>
      <% if user.id != @wiki.user_id %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td>
            <% if not_collaborator?(@wiki.collaborators, user.id) %>
              <%= link_to "Add", wiki_collaborators_path(user_id: user.id, wiki: @wiki), method: :post, class: 'btn btn-success' %>
            <% else %>
              <%= link_to "Remove", wiki_collaborator_path(user_id: user.id, id: @wiki.collaborators.find_by_user_id(user.id).id), method: :delete, class: 'btn btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>
</div>

app/views/collaborators/new.html.erb
<h1>New collaborators</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/showdown/1.7.1/showdown.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Blocipedia", root_path %></li>
      <li><%= link_to "My Wikis", wikis_path %></li>

      <div class="pull-right user-info col-xs-12">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.name %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navnar-link' %> -
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <% if !user_is_premium? %>
             - <%= link_to 'Upgrade Account', new_charge_path, :class => 'navbar-link' %>
          <% end %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </div>
    </ul>
  </br>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>


    <%= yield %>
  </div>

</body>
</html>

app/views/welcome/index.html.erb
<h1 class="text-center">Blocipedia: Social, Markdown Wikis</h1>

<br/>
  <div class="jumbotron text-center pagination-centered">
    <h3>Create and share Markdown Wikis</h3>
    </br>
    <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-success text-center' %>
  </div>
</br>
<div class="row">
  <div class="col-md-6 text-center">
    <h4>Create as many public</h4>
    <h4>wikis as you want!</h4>
    <div><%= image_tag("glyphicons-20-heart-empty.png", :alt => "heart") %></div>
    <p>Free Plan</p>
  </div>
  <div class="col-md-6 text-center">
    <h4>Create private wikis!</h4>
    </br>
    <div><%= image_tag("glyphicons-66-tag.png", :alt => "tag") %></div>
    <p>Premium Plan</p>
  </div>
</div>

app/views/wikis/_wiki.html.erb
<p><%= markdown(@wiki.body) %></p>

app/views/wikis/_wiki_preview.html.erb
<p><%= preview(@wiki.body) %></p>

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
<% if @wiki.user == current_user || current_user.admin? %>
  <%= link_to "Add collaborators", wiki_collaborators_path(@wiki), class: 'btn btn-success' %>
<% end %>
<div class="row">
  <div class="col-md-6">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter wiki title' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 20, class: 'form-control', id: 'sourceTA', onkeyup: 'run()', placeholder: 'Enter wiki body' %>
      </div>
      <% if current_user.premium? || current_user.admin? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-6" id="targetDiv"></div>
</div>

app/views/wikis/index.html.erb
<h1 class="text-center">My Wikis</h1>
</br>
<div class="wiki-table">
  <table class="table table-striped">
    <% @wikis.each do |wiki| %>
      <tr>
        <td><%= link_to markdown(wiki.title), wiki %></td>
        <td>
          <% if policy(wiki).edit? %>
            <%= link_to "edit", edit_wiki_path(wiki) %>
          <% end %>
        </td>
        <td>
          <% if policy(wiki).destroy? %>
            <%= link_to "delete", wiki, method: :delete, data: {confirm: 'Are you sure you want to delete this wiki?'} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>
</br>
<div class="text-center">
  <% if user_signed_in? %>
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  <% end %>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-6">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: 'Enter wiki title' %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 20, class: 'form-control', id: 'sourceTA', onkeyup: 'run()', placeholder: 'Enter wiki body' %>
      </div>
      <% if current_user.premium? || current_user.admin? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
  <div class="col-md-6" id="targetDiv"></div>
</div>

app/views/wikis/show.html.erb
<h1><%= markdown(@wiki.title) %></h1>
<% if policy(@wiki).update? %>
  <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>
<% if policy(@wiki).destroy? %>
  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
<% end %>

<%= render partial: 'wikis/wiki', locals: { wiki: @wiki } %>